# Gradle Properties
    org.gradle.jvmargs=-Xmx6G -XX:+UseG1GC -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
    org.gradle.parallel=true
    org.gradle.configuration-cache=true
    org.gradle.caching=true
    org.gradle.daemon=true
    org.gradle.configuration-cache.parallel=true
    org.gradle.daemon.idletimeout=3600000

# Fabric Basic Properties
	# https://fabricmc.net/versions.html
	loader_version=0.19.5
    fabric.loom.preferGradleTask=true

# Mod Properties
	mod_id=carpet-igny-addition
	mod_name=Carpet IGNY Addition
	mod_version=1.17.1
	maven_group=com.liuyue.igny
	archives_base_name=carpet-igny-addition
org.gradle.java.home=G:/Downloads/jdk-25_windows-x64_bin/jdk-25
