# Fabric Properties
# check these on https://fallen-breath.github.io/fabric-versions/?&version=26.3
minecraft_version=26.3

# Fabric Mod Metadata
carpet_dependency=>=26.3
minecraft_dependency=>=26.3-

# Build Information
# The target mc versions for the mod during mod publishing, separated with \n
game_versions=26.3

# Mod Dependency
# check available versions on maven for the given minecraft version you are using
# https://masa.dy.fi/maven/carpet/fabric-carpet/
carpet_core_version = 26.3+v260915

# Dependencies
fabric_api_version=0.160.6+26.3
lithium_dependency=com.github.Fallen-Breath:lithium-fabric:34966dcdad
ryansrenderingkit_version=1.3.0+26.3
syncmatica_version=26.2-0.3.20
starlight_dependency=maven.modrinth:Ps1zyz6x:EKLUURiy
litematica_dependency=fi.dy.masa.litematica:litematica-fabric-26.3:0.29.0
malilib_dependency=fi.dy.masa.malilib:malilib-fabric-26.3:0.30.1
servux_dependency=fi.dy.masa.servux:servux-fabric-26.2:0.11.5
minihud_dependency=fi.dy.masa.minihud:minihud-fabric-26.3:0.41.1
